name: Update image to dockerhub and run a new instance

on:
  push:
    branches: 
      - "main" 

jobs:
    
  deploy-ansible:

    runs-on: ubuntu-latest
    #needs: update_image
    steps:
    
    - name: Clone frances-joffany-navarro/upskill-devops
      uses: actions/checkout@v4
      with:
        repository: 'frances-joffany-navarro/upskill-devops'
        path: upskill-devops
    
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: playbook.yaml
        directory: ./upskill-devops/ansible-automation/automate-deployment
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        inventory: |
          [aws_host]
          ec2-13-60-89-88.eu-north-1.compute.amazonaws.com
          
          [aws_host:vars]
          ansible_user=ubuntu

        options: |
          --extra-vars "docker_username=iamfrancesjoffany docker_token=${{ secrets.DOCKERHUB_TOKEN }}"
          -vvv
          --ssh-extra-args "-o StrictHostKeyChecking=no"
